name: Run tests
on: push

jobs:
  build:
    name: Run tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Cache Modules
        uses: actions/cache@v1
        id: cache
        with:
          path: ps_modules
          key: ${{ runner.os }}-PSModules

      - name: Install Pester
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir ps_modules
          Find-Module Pester | Save-Module -Path ./ps_modules/
        shell: pwsh

      - name: Run the tests
        id: run_tests
        run: |
          echo 'Running tests...'
          Import-Module ./ps_modules/Pester
          Get-Module | select name, path | Out-Host
          $outDir = New-Item ./_reports/ -ItemType Directory
          $reportPath = "$outDir/testResults.xml"
          $coveragePath = "$outDir/coverage.xml"
          $src = Get-ChildItem ./cd-extras -Recurse -File -Include *.ps1
          cd tests
          Invoke-Pester -OutputFormat JUnitXml -OutputFile $reportPath `
            -CodeCoverage $src -CodeCoverageOutputFile $coveragePath -EnableExit
        shell: pwsh

      - name: Upload test report
        uses: actions/upload-artifact@master
        with:
          name: Test Report (${{ matrix.os }})
          path: _reports